apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dataaccess
  namespace: microservice0
  labels:
    app.kubernetes.io/name: dataaccess
    app.kubernetes.io/part-of: microservice0
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataaccess
