apiVersion: v1
kind: ConfigMap
metadata:
  name: management-config
  namespace: microservice0
  labels:
    app.kubernetes.io/name: management
    app.kubernetes.io/part-of: microservice0
    app.kubernetes.io/component: backend
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  GrpcClients__UserRepositoryService: "http://dataaccess.microservice0.svc.cluster.local:8080"
