apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: management
  namespace: microservice0
  labels:
    app.kubernetes.io/name: management
    app.kubernetes.io/part-of: microservice0
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: management
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
