apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice0.labels" (dict "name" "gateway" "component" "frontend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
