<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\libs\Shared.Common\Shared.Common.csproj" />
    <ProjectReference Include="..\..\..\libs\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\..\..\libs\Shared.Protos\Shared.Protos.csproj" />
  </ItemGroup>

</Project>
