apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dataaccess
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice0.labels" (dict "name" "dataaccess" "component" "backend") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dataaccess
  minReplicas: {{ .Values.dataaccess.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dataaccess.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.dataaccess.autoscaling.targetCPUUtilizationPercentage }}
