<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Protobuf Include="Protos\common.proto" ProtoRoot="Protos" GrpcServices="None" />
    <Protobuf Include="Protos\user_management.proto" ProtoRoot="Protos" GrpcServices="Both" />
    <Protobuf Include="Protos\user_repository.proto" ProtoRoot="Protos" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
