apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: management
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice0.labels" (dict "name" "management" "component" "backend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.management.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: management
